### ISSUE TITLE
Add cluster information section to the clusters list

### ISSUE THREAD

**Issue by lefreud** [ComputeCanada/mc-hub#26]
Right now, as mentionned in https://github.com/ComputeCanada/mc-hub/issues/21, in order to find the generated guest password of a cluster, the user needs to go back to the cluster editor to copy and paste it, which doesn't make sense.

Also, the FreeIPA admin password, generated randomly by Terraform, is not displayed anywhere. Showing this information to users will help them manage the users in the FreeIPA interface.

For now, the information would be probably shown in the following format:
Sudoer username: `fredfc`
Guest usernames: `user01-user50`
Guest password: `r75mGH274`
Admin password: `jmbsSD3e7d`

We are looking for the best way of displaying these cluster information to the end user within the cluster list of MC Hub. Eventually, other useful cluster information could be added, such as the cluster's uptime.

Here are a few ways to implement this feature:

- Adding a section on the bottom when the user selects a cluster with a checkbox, similar to the following screenshot of AWS's EC2 dashboard. ![image](https://user-images.githubusercontent.com/35122940/98391918-4a751d00-2025-11eb-8287-5ee7f1f5c861.png)
- Displaying the same information with Vuetify's expandable rows: https://vuetifyjs.com/en/components/data-tables/#expandable-rows
- Displaying the same information with a dialog box: https://vuetifyjs.com/en/components/dialogs

Which option do you prefer?

**Comment by cmd-ntrf** [comment]
Supersedes issue #21

**Comment by lefreud** [comment]
The cluster information section is now functional in https://github.com/ComputeCanada/mc-hub/commit/d1b29ac31f1d24617b6a81d66e1c1c1698ddd07c.
