### ISSUE TITLE
Log rotate the logs every time there is a new apply or destroy

### ISSUE THREAD

**Issue by cmd-ntrf** [ComputeCanada/mc-hub#32]
MC-Hub currently overwrites the previous apply log when applying again.

MC-Hub should either append to existing log file, or rename the existing file to something like `apply.log.1`  if the file already exists.

**Comment by lefreud** [comment]
Yes indeed, I'll look into improving the logging for the next release.

**Comment by lefreud** [comment]
I implemented log rotation in https://github.com/ComputeCanada/mc-hub/commit/9cb2436cacd6b1d915d2d9ddfa38f309c45f39e5.

The most recent `terraform apply` log file will be named `terraform_apply.log` and the older logs will be named `terraform_apply.log.1`, `terraform_apply.log.2`, etc. The same is done for `terraform plan` logs, except the file name starts with `terraform_plan.log`. Destroy logs are also stored the same way.
